steps:
  - label: "🚀 Deploy to dev"
    command: "scripts/deploy.sh"
    if: build.branch == 'main'
    concurrency: 1
    concurrency_group: "eft-sure-deploy-dev"
    key: "deploy-dev"

  - wait: ~

  - block: "🚀 Deploy to staging?"
    prompt: "Do you want to promote this build to the staging environment?"
    depends_on: "deploy-dev"
    branches: 
      - "main"
    fields: 
    - text: "Release Name"
      key: "release-name"
      hint: "Think of a cool name for this release"
    - select: "Type"
      key: "release-type"
      default: "staging"
      options:
      - label: "Staging"
        value: "staging"
      - label: "Production"
        value: "prod"
  - command: scripts/deploy.sh
    label: ":rocket:"
