steps:
  - block: "Confirm deployment to staging"

  - label: "🚀 Deploy to staging"
    command: echo "Deploying to staging"
    if: build.branch == 'main'
    concurrency: 1
    concurrency_group: "eft-sure-deploy-staging"
    key: "deploy-staging"
 
  - wait: ~

  - block: "🚀 Deploy to prod?"
    depends_on: "deploy-staging"
    prompt: "Do you want to promote this build to the prod environment?"
    branches: 
      - "main"
    fields: 
    - select: "Type"
      key: "release-type"
      default: "prod"
      options:
      - label: "Production"
        value: "prod"
  - command: scripts/deploy.sh
    label: ":rocket:"
