steps:
  - block: "Deploy to staging?"
  - label: "🚀 Deploy to staging"
    command: "scripts/deploy staging"
    if: build.branch == 'main'
    concurrency: 1
    concurrency_group: "eft-sure-deploy-staging"
