steps:
  - block: "Deploy to prod?"
  - label: "🚀 Deploy to prod"
    command: echo "Deploying to prod"
    if: build.branch == 'main'
    concurrency: 1
    concurrency_group: "eft-sure-deploy-prod"
