# .buildkite/tests.pipeline.yml
steps:
  - label: "🔧 Run Tests"
    command: "scripts/tests.sh"

  - wait
  
  - block: "Promote this to dev?"
    prompt: "Do you want to promote this build?"
    branches: 
      - "main"
    fields: 
      - text: "Release Name"
        key: "release-name"
      - select: "Type"
        key: "release-type"
        default: "dev"
        options:
        - label: "Development"
          value: "dev"
        - label: "Staging"
          value: "staging"
        - label: "Production"
          value: "prod"
  - command: scripts/deploy.sh
    label: ":rocket:"
